#!/bin/bash

# Nombre del trabajo
#PBS -N 1_1_long

# Requerimientos
# En este caso nuestro trabajo requiere: 16 procesadores, 1 hora de ejecución.
#PBS -l nodes=1,walltime=24:00:00

# Cola de ejecución
#PBS -q small_jobs

# Directorio de trabajo
#PBS -d /home/siturria/github/cloud-cdn/jmetal4.5

# Correo electronico
#PBS -M siturria@fing.edu.uy

# Email
#PBS -m abe
# n: no mail will be sent.
# a: mail is sent when the job is aborted by the batch system.
# b: mail is sent when the job begins execution.
# e: mail is sent when the job terminates.

# Directorio donde se guardará la salida estándar y de error de nuestro trabajo
#PBS -e /home/siturria/github/cloud-cdn/jmetal4.5/
#PBS -o /home/siturria/github/cloud-cdn/jmetal4.5/

# Will make  all variables defined in the environment from which the job is submitted available to the job.
###PBS -V

echo Job Name: $PBS_JOBNAME
echo Working directory: $PBS_O_WORKDIR
echo Queue: $PBS_QUEUE
echo Cantidad de tasks: $PBS_TASKNUM
echo Home: $PBS_O_HOME
echo Puerto del MOM: $PBS_MOMPORT
echo Nombre del usuario: $PBS_O_LOGNAME
echo Idioma: $PBS_O_LANG
echo Cookie: $PBS_JOBCOOKIE
echo Offset de numero de nodos: $PBS_NODENUM
echo Shell: $PBS_O_SHELL
echo Host: $PBS_O_HOST
echo Cola de ejecucion: $PBS_QUEUE
echo Archivo de nodos: $PBS_NODEFILE
echo Path: $PBS_O_PATH
echo
cd $PBS_O_WORKDIR
echo Current path:
pwd
echo
echo Nodos:
cat $PBS_NODEFILE
echo
echo Cantidad de nodos:
NPROCS=$(wc -l < $PBS_NODEFILE)
echo $NPROCS
echo

/home/siturria/bin/jdk1.8.0_77/bin/java -classpath ../bin jmetal.experiments.studies.CloudCDN_f201603_long_SMSEMOA low 0 43200 1 1